title: Diabetic Retinopathy Detection using Deep Learning Model
description: Rate presence of Diabetic Retinopathy
about:


  This is a Diabetic Retinopathy Detector that detects Referrable Diabetic Retinopathy (RDR) using Deep Learning and was built with [fastai](docs.fast.ai)


  This project was built by [Tanishq Abraham](https://github.com/tmabraham). I am just Implementing it for the learning purpose


  The web application was based on the [Food Image Classifier by Nidhin Pattaniyil and Reshama Shaikh](https://reshamas.github.io/deploying-deep-learning-models-on-web-and-mobile/)


code: https://github.com/mdsharique/Retinopathy_Detection

sampleImages:
  - name: No Retinopathy
    url: https://i.imgur.com/fZGFzgA.jpg
  - name: Mild Nonproliferative Retinopathy
    url: https://i.imgur.com/a3dYWum.jpg
  - name: Moderate Nonproliferative Retinopathy
    url: https://i.imgur.com/dIz4r2Y.jpg
  - name: Severe Nonproliferative Retinopathy
    url: https://i.imgur.com/qYMsGiT.jpg
  - name: Proliferative Diabetic Retinopathy
    url: https://i.imgur.com/gyLdo86.jpg
